class AppLocalization {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'dns': 'DNS',
      'explore': 'Explore',
      'add_dns': 'Add DNS',
      'settings': 'Settings',
      'about': 'About Us',
      'test_ping': 'Test Ping',
      'pinging': 'Pinging...',
      'failed': 'Failed',
      'click_connect': 'Click to connect',
      'click_disconnect': 'Click to disconnect',
      'please_wait': 'Please wait...',
      'dns_active': 'DNS is active',
      'dns_off': 'DNS is off',
      'no_dns_selected': 'No DNS Selected',
      'explore_public_dns': 'Explore Public DNS',
      'refresh_list': 'Refresh List',
      'search_hint': 'Search by name or IP...',
      'no_matches': 'No DNS matches found',
      'add_to_local': 'Add to local DNS',
      'added_to_local': 'added to local list!',
      'already_in_list': 'is already in the list!',
      'add_custom_dns': 'Add Custom DNS',
      'dns_name_hint': 'DNS Name (e.g. My Secure DNS)',
      'primary_ip_hint': 'Primary IP (e.g. 1.1.1.1)',
      'secondary_ip_hint': 'Secondary IP (Optional)',
      'save_custom_dns': 'Save Custom DNS',
      'your_saved_custom_dns': 'Your Saved Custom DNS:',
      'no_custom_dns_yet': 'No custom DNS added yet.',
      'delete': 'Delete',
      'custom_dns_saved': 'Custom DNS saved successfully!',
      'ip_exists': 'DNS with these IPs already exists!',
      'required': 'Required',
      'primary_ip_required': 'Primary IP is required',
      'invalid_ipv4': 'Invalid IPv4 address format',
      'flush_dns': 'Flush DNS',
      'clear_cache': 'Clear system DNS cache',
      'theme_dark': 'Dark Theme',
      'theme_light': 'Light Theme',
      'theme_red': 'Red Theme',
      'theme_green': 'Green Theme',
      'launch_startup': 'Run at Startup',
      'language': 'Language',
    },
    'fa': {
      'dns': 'دی‌ان‌اس',
      'explore': 'کاوشگر',
      'add_dns': 'افزودن دی‌ان‌اس',
      'settings': 'تنظیمات',
      'about': 'درباره ما',
      'test_ping': 'تست پینگ',
      'pinging': 'در حال پینگ...',
      'failed': 'خطا داد',
      'click_connect': 'برای اتصال کلیک کنید',
      'click_disconnect': 'برای قطع کلیک کنید',
      'please_wait': 'کمی صبر کنید...',
      'dns_active': 'دی‌ان‌اس فعال است',
      'dns_off': 'دی‌ان‌اس خاموش است',
      'no_dns_selected': 'هیچ دی‌ان‌اسی انتخاب نشده',
      'explore_public_dns': 'لیست دی‌ان‌اس‌های عمومی',
      'refresh_list': 'به‌روزرسانی لیست',
      'search_hint': 'جستجو با نام یا آی‌پی...',
      'no_matches': 'هیچ دی‌ان‌اسی یافت نشد',
      'add_to_local': 'افزودن به لیست من',
      'added_to_local': 'به لیست شما اضافه شد!',
      'already_in_list': 'هم‌اکنون در لیست وجود دارد!',
      'add_custom_dns': 'افزودن دی‌ان‌اس دستی',
      'dns_name_hint': 'نام (مثال: دی‌ان‌اس من)',
      'primary_ip_hint': 'آی‌پی اول (مثال: 1.1.1.1)',
      'secondary_ip_hint': 'آی‌پی دوم (اختیاری)',
      'save_custom_dns': 'ذخیره دی‌ان‌اس',
      'your_saved_custom_dns': 'دی‌ان‌اس‌های ذخیره‌شده شما:',
      'no_custom_dns_yet': 'هنوز دی‌ان‌اسی اضافه نکرده‌اید.',
      'delete': 'حذف',
      'custom_dns_saved': 'با موفقیت ذخیره شد!',
      'ip_exists': 'دی‌ان‌اسی با این آی‌پی‌ها وجود دارد!',
      'required': 'الزامی است',
      'primary_ip_required': 'آی‌پی اول الزامی است',
      'invalid_ipv4': 'فرمت آی‌پی نامعتبر است',
      'flush_dns': 'پاک‌سازی دی‌ان‌اس',
      'clear_cache': 'کش دی‌ان‌اس سیستم خالی شود',
      'theme_dark': 'تم تاریک',
      'theme_light': 'تم روشن',
      'theme_red': 'تم قرمز',
      'theme_green': 'تم سبز',
      'launch_startup': 'اجرا هنگام بالا آمدن ویندوز',
      'language': 'زبان برنامه',
    },
    'zh': {
      'dns': 'DNS',
      'explore': '探索',
      'add_dns': '添加 DNS',
      'settings': '设置',
      'about': '关于我们',
      'test_ping': '测试延迟',
      'pinging': 'Ping...',
      'failed': '失败',
      'click_connect': '点击连接',
      'click_disconnect': '点击断开',
      'please_wait': '请稍候...',
      'dns_active': 'DNS 已启动',
      'dns_off': 'DNS 已关闭',
      'no_dns_selected': '未选择 DNS',
      'explore_public_dns': '探索公共 DNS',
      'refresh_list': '刷新列表',
      'search_hint': '按名称或 IP 搜索...',
      'no_matches': '未找到匹配的 DNS',
      'add_to_local': '添加到本地 DNS',
      'added_to_local': '已添加到本地列表！',
      'already_in_list': '已在列表中！',
      'add_custom_dns': '添加自定义 DNS',
      'dns_name_hint': 'DNS 名称 (例如 My Secure DNS)',
      'primary_ip_hint': '首选 IP (例如 1.1.1.1)',
      'secondary_ip_hint': '备用 IP (可选)',
      'save_custom_dns': '保存自定义 DNS',
      'your_saved_custom_dns': '您保存的自定义 DNS:',
      'no_custom_dns_yet': '尚未添加自定义 DNS。',
      'delete': '删除',
      'custom_dns_saved': '自定义 DNS 保存成功！',
      'ip_exists': '具有这些 IP 的 DNS 已存在！',
      'required': '必填',
      'primary_ip_required': '首选 IP 是必填',
      'invalid_ipv4': '无效的 IPv4 格式',
      'flush_dns': '刷新 DNS',
      'clear_cache': '清除系统 DNS 缓存',
      'theme_dark': '黑暗主题',
      'theme_light': '精简主题',
      'theme_red': '红色主题',
      'theme_green': '绿色主题',
      'launch_startup': '开机时启动',
      'language': '语言',
    },
    'es': {
      'dns': 'DNS',
      'explore': 'Explorar',
      'add_dns': 'Añadir DNS',
      'settings': 'Ajustes',
      'about': 'Acerca de',
      'test_ping': 'Probar Ping',
      'pinging': 'Haciendo ping...',
      'failed': 'Falló',
      'click_connect': 'Haz clic para conectar',
      'click_disconnect': 'Haz clic para desconectar',
      'please_wait': 'Por favor espera...',
      'dns_active': 'DNS está activo',
      'dns_off': 'DNS está apagado',
      'no_dns_selected': 'No hay DNS seleccionado',
      'explore_public_dns': 'Explorar DNS público',
      'refresh_list': 'Actualizar lista',
      'search_hint': 'Buscar por nombre o IP...',
      'no_matches': 'No se encontraron coincidencias de DNS',
      'add_to_local': 'Añadir a DNS local',
      'added_to_local': 'añadido a la lista local!',
      'already_in_list': 'ya está en la lista!',
      'add_custom_dns': 'Añadir DNS Personalizado',
      'dns_name_hint': 'Nombre DNS (ej. DNS Seguro)',
      'primary_ip_hint': 'IP Primaria (ej. 1.1.1.1)',
      'secondary_ip_hint': 'IP Secundaria (Opcional)',
      'save_custom_dns': 'Guardar DNS Personalizado',
      'your_saved_custom_dns': 'Tus DNS personalizados guardados:',
      'no_custom_dns_yet': 'Aún no se ha añadido un DNS personalizado.',
      'delete': 'Eliminar',
      'custom_dns_saved': '¡DNS personalizado guardado con éxito!',
      'ip_exists': '¡El DNS con estas IP ya existe!',
      'required': 'Requerido',
      'primary_ip_required': 'Se requiere la IP principal',
      'invalid_ipv4': 'Formato de dirección IPv4 no válido',
      'flush_dns': 'Limpiar DNS',
      'clear_cache': 'Limpiar la caché de DNS del sistema',
      'theme_dark': 'Tema oscuro',
      'theme_light': 'Tema ligero',
      'theme_red': 'Tema rojo',
      'theme_green': 'Tema verde',
      'launch_startup': 'Ejecutar al inicio',
      'language': 'Idioma',
    },
    'ru': {
      'dns': 'DNS',
      'explore': 'Обследовать',
      'add_dns': 'Добавить DNS',
      'settings': 'Настройки',
      'about': 'О нас',
      'test_ping': 'Проверить пинг',
      'pinging': 'Пинг...',
      'failed': 'Ошибка',
      'click_connect': 'Нажмите для подключения',
      'click_disconnect': 'Нажмите для отключения',
      'please_wait': 'Пожалуйста, подождите...',
      'dns_active': 'DNS активен',
      'dns_off': 'DNS выключен',
      'no_dns_selected': 'DNS не выбран',
      'explore_public_dns': 'Исследуйте публичные DNS',
      'refresh_list': 'Обновить список',
      'search_hint': 'Поиск по имени или IP...',
      'no_matches': 'Совпадений DNS не найдено',
      'add_to_local': 'Добавить в локальный DNS',
      'added_to_local': 'добавлено в локальный список!',
      'already_in_list': 'уже в списке!',
      'add_custom_dns': 'Добавить пользовательский DNS',
      'dns_name_hint': 'Имя DNS (например, My Secure DNS)',
      'primary_ip_hint': 'Основной IP (например, 1.1.1.1)',
      'secondary_ip_hint': 'Дополнительный IP (необязательно)',
      'save_custom_dns': 'Сохранить пользовательский DNS',
      'your_saved_custom_dns': 'Ваши сохраненные пользовательские DNS:',
      'no_custom_dns_yet': 'Пользовательские DNS еще не добавлены.',
      'delete': 'Удалить',
      'custom_dns_saved': 'Пользовательский DNS успешно сохранен!',
      'ip_exists': 'DNS с этими IP уже существует!',
      'required': 'Обязательный',
      'primary_ip_required': 'Требуется основной IP',
      'invalid_ipv4': 'Неверный формат адреса IPv4',
      'flush_dns': 'Очистить DNS',
      'clear_cache': 'Очистить системный кэш DNS',
      'theme_dark': 'Темная тема',
      'theme_light': 'Светлая тема',
      'theme_red': 'Красная тема',
      'theme_green': 'Зеленая тема',
      'launch_startup': 'Запуск при загрузке',
      'language': 'Язык',
    }
  };

  static String get(String locale, String key) {
    return translations[locale]?[key] ?? translations['en']?[key] ?? key;
  }
}
